version: '3.7'

services:
    postgresql:
        container_name: postgresql
        restart: always
        image: postgres:latest
        ports:
            - 5432:5432
        volumes:
            - ./db:/var/lib/postgresql/data
        environment:
            - POSTGRES_DB=project-docker
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=admin

    api_docker:
        container_name: dockerized_api
        restart: always
        build:
            context: .
            dockerfile: Dockerfile
            target: base
        ports:
            - 3000:3000
        command: npm run start
        env_file: .env
        environment:
            PG_HOST: postgresql
            PG_USER: postgres
            PG_DATABASE: project-docker
            PG_PASSWORD: admin
            PG_PORT: 5432
            API_PORT: 3000

volumes:
    db:
        external: true